### ISSUE TITLE
picoモーターのテスト機をVer.2で動かす。

### ISSUE THREAD

**Issue by RyoheiKozuicrr** [MiyoKouseki/epics-motor-control#6]
## Todo
- [x] ネットワークの設定
- [x] 新しいVersion対応のMedmをSitemapから開けるようにする。
- [x] happy_pico_start.pyを/kagra/bin/happy_pico_startにリンクを貼ってコマンドにする
- [x] 完了

## 参照
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/DGS/Projects/PicoMotor#preview

**Comment by MiyoKouseki** [comment]
close
